a = input()
b = input()
print("a =", a)
print("b =", b)
print("a + b =", float(a) + float(b))
print("a - b =", float(a) - float(b))
print("b - a =", float(b) - float(a))
print("a * b =", float(a) * float(b))
print("a / b =", float(a) / float(b))
print("b / a =", float(b) / float(a))

print("/ - целочисленное деление в C++")
print("В Python целочисленное деление - //")